### ISSUE TITLE
The latest master/3.0.0 Matt fails to compile on macOS 10.14.5

### ISSUE THREAD

**Issue by NordicFlyer** [jimmykane/quantified-self#158]
The latest master/3.0.0 Matt fails to compile on macOS 10.14.5. 

[Terminal Saved Output 06052019.pdf](https://github.com/jimmykane/quantified-self/files/3257883/Terminal.Saved.Output.06052019.pdf)

**Comment by jimmykane** [comment]
There he is! 

Fixing asap.

**Comment by NordicFlyer** [comment]
Update on compile fail status? Thank you.

**Comment by jimmykane** [comment]
Yes release is bound this weekend. 

Here is what has been worked on 
<img width="944" alt="Screenshot 2019-06-14 at 16 46 22" src="https://user-images.githubusercontent.com/1268723/59517904-e1878500-8ec4-11e9-8a75-8364afe7e231.png">

**Comment by NordicFlyer** [comment]
Very cool! Thanks for the update. Cheers!

**Comment by jimmykane** [comment]
Should be now ok

**Comment by NordicFlyer** [comment]
Still having build errors and other issues identical to #161 and #162. Thanks.

**Comment by jimmykane** [comment]
Looking into it

**Comment by NordicFlyer** [comment]
@jimmykane I found a workaround using 'npm' to compile 3.0.0 Matt on macOS 10.14.5 here: https://github.com/webpack/webpack/issues/8656

Basically, assuming one has 'node.js' installed on their system, it is relatively simple as follows:

npm install acorn
npm install acorn-dynamic-import
npm update acorn --depth 20
npm dedupe
npm install
npm start

see terminal output: 
[Terminal Saved Output 06282019_1.pdf](https://github.com/jimmykane/quantified-self/files/3340913/Terminal.Saved.Output.06282019_1.pdf)

Utilizing 'yarn' to compile 3.0.0 Matt results in too many errors on my system. The same can be said for the latest master. The build errors as in #161 and #162 still exist to date.

Thanks for your excellent work. Hopefully, a new release is in the works that will compile easily on the latest macOS. Cheers!

**Comment by jimmykane** [comment]
Yeah that is the main reason I moved away from npm. 
The error in master  / develop is due to a propertiary font I should not source control. 
I have thought about workarrounds and I am almost sure I have a solution. 

I am now working on 3.8.x (release) so I will include this.

**Comment by NordicFlyer** [comment]
Thanks for your response. I am looking forward to the 3.8.x release. Have a great day!

**Comment by jimmykane** [comment]
can you check with 3.8.3 ?

**Comment by NordicFlyer** [comment]
Lots of build errors utilizing yarn on latest master.

`ERROR in src/app/components/cards/event/chart/event.card.chart.component.ts(141,44): error TS2339: Property 'getUnitStreamsFromStreams' does not exist on type 'typeof EventUtilities'.
src/app/components/cards/event/devices/event.card.devices.component.ts(30,24): error TS2339: Property 'name' does not exist on type 'DeviceInterface'.
src/app/components/cards/event/stats/event.card.stats.component.ts(47,32): error TS2339: Property 'isUnitDerivedDataType' does not exist on type 'typeof DynamicDataLoader'.
src/app/components/charts/actions/chart.actions.component.ts(14,47): error TS2307: Cannot find module 'quantified-self-lib/lib/users/user.dashboard.chart.settings.interface'.
src/app/components/charts/actions/chart.actions.component.ts(33,28): error TS2307: Cannot find module 'quantified-self-lib/lib/data/data.peak-epoc'.
src/app/components/charts/actions/chart.actions.component.ts(121,24): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/charts/actions/chart.actions.component.ts(124,26): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/charts/actions/chart.actions.component.ts(130,24): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/charts/actions/chart.actions.component.ts(135,24): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/charts/column/charts.column.component.ts(22,35): error TS2307: Cannot find module 'quantified-self-lib/lib/users/user.dashboard.chart.settings.interface'.
src/app/components/charts/pie/charts.pie.component.ts(20,35): error TS2307: Cannot find module 'quantified-self-lib/lib/users/user.dashboard.chart.settings.interface'.
src/app/components/dashboard/dashboard.component.ts(9,26): error TS2307: Cannot find module 'quantified-self-lib/lib/users/user.dashboard.settings.interface'.
src/app/components/dashboard/dashboard.component.ts(13,9): error TS2305: Module '"../../../../node_modules/quantified-self-lib/lib/users/user.unit.settings.interface"' has no exported member 'DaysOfTheWeek'.
src/app/components/dashboard/dashboard.component.ts(53,30): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(53,102): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(53,152): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(54,60): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(55,58): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(58,70): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(58,131): error TS2339: Property 'startOfTheWeek' does not exist on type 'UserUnitSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(59,68): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(59,129): error TS2339: Property 'startOfTheWeek' does not exist on type 'UserUnitSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(60,61): error TS2339: Property 'startOfTheWeek' does not exist on type 'UserUnitSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(71,24): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(72,24): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/dashboard/dashboard.component.ts(73,24): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/event-form/event.form.component.ts(54,47): error TS2339: Property 'description' does not exist on type 'EventInterface'.
src/app/components/event-form/event.form.component.ts(62,43): error TS2339: Property 'isMerge' does not exist on type 'EventInterface'.
src/app/components/event-search/event-search.component.ts(4,26): error TS2307: Cannot find module 'quantified-self-lib/lib/users/user.dashboard.settings.interface'.
src/app/components/event-search/event-search.component.ts(5,9): error TS2305: Module '"../../../../node_modules/quantified-self-lib/lib/users/user.unit.settings.interface"' has no exported member 'DaysOfTheWeek'.
src/app/components/event-table/event.table.component.ts(35,33): error TS2307: Cannot find module 'quantified-self-lib/lib/data/data.activity-types'.
src/app/components/event-table/event.table.component.ts(36,31): error TS2307: Cannot find module 'quantified-self-lib/lib/data/data.device-names'.
src/app/components/event-table/event.table.component.ts(262,43): error TS2339: Property 'isMerge' does not exist on type 'EventInterface'.
src/app/components/history-import-form/history-import.form.component.ts(15,40): error TS2307: Cannot find module 'quantified-self-lib/lib/users/user.service.meta.interface'.
src/app/components/history-import-form/history-import.form.component.ts(17,28): error TS2307: Cannot find module 'quantified-self-lib/lib/meta-data/meta-data.interface'.
src/app/components/login/login.component.ts(13,37): error TS2307: Cannot find module 'quantified-self-lib/lib/service-tokens/service-token.interface'.
src/app/components/services/services.component.ts(17,37): error TS2307: Cannot find module 'quantified-self-lib/lib/service-tokens/service-token.interface'.
src/app/components/services/services.component.ts(18,28): error TS2307: Cannot find module 'quantified-self-lib/lib/meta-data/meta-data.interface'.
src/app/components/summaries/summaries.component.ts(11,33): error TS2307: Cannot find module 'quantified-self-lib/lib/data/data.activity-types'.
src/app/components/summaries/summaries.component.ts(18,8): error TS2307: Cannot find module 'quantified-self-lib/lib/users/user.dashboard.chart.settings.interface'.
src/app/components/summaries/summaries.component.ts(104,51): error TS2339: Property 'isMerge' does not exist on type 'EventInterface'.
src/app/components/summaries/summaries.component.ts(105,75): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/components/user-forms/user-agreement.form.component.ts(12,37): error TS2307: Cannot find module 'quantified-self-lib/lib/service-tokens/service-token.interface'.
src/app/components/user-forms/user.form.component.ts(67,52): error TS2339: Property 'brandText' does not exist on type 'User'.
src/app/components/user-settings/user-settings.component.ts(19,3): error TS2305: Module '"../../../../node_modules/quantified-self-lib/lib/users/user.unit.settings.interface"' has no exported member 'DaysOfTheWeek'.
src/app/components/user-settings/user-settings.component.ts(93,71): error TS2339: Property 'startOfTheWeek' does not exist on type 'UserUnitSettingsInterface'.
src/app/components/user-settings/user-settings.component.ts(152,49): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/services/app.event.service.ts(27,31): error TS2307: Cannot find module 'quantified-self-lib/lib/data/data.device-names'.
src/app/services/app.user.service.ts(19,3): error TS2305: Module '"../../../node_modules/quantified-self-lib/lib/users/user.unit.settings.interface"' has no exported member 'DaysOfTheWeek'.
src/app/services/app.user.service.ts(28,37): error TS2307: Cannot find module 'quantified-self-lib/lib/service-tokens/service-token.interface'.
src/app/services/app.user.service.ts(30,28): error TS2307: Cannot find module 'quantified-self-lib/lib/meta-data/meta-data.interface'.
src/app/services/app.user.service.ts(31,40): error TS2307: Cannot find module 'quantified-self-lib/lib/users/user.service.meta.interface'.
src/app/services/app.user.service.ts(35,8): error TS2307: Cannot find module 'quantified-self-lib/lib/users/user.dashboard.settings.interface'.
src/app/services/app.user.service.ts(39,8): error TS2307: Cannot find module 'quantified-self-lib/lib/users/user.dashboard.chart.settings.interface'.
src/app/services/app.user.service.ts(237,27): error TS2339: Property 'startOfTheWeek' does not exist on type 'UserUnitSettingsInterface'.
src/app/services/app.user.service.ts(237,66): error TS2339: Property 'startOfTheWeek' does not exist on type 'UserUnitSettingsInterface'.
src/app/services/app.user.service.ts(238,14): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/services/app.user.service.ts(238,43): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/services/app.user.service.ts(239,14): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/services/app.user.service.ts(239,53): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/services/app.user.service.ts(240,14): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/services/app.user.service.ts(240,53): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/services/app.user.service.ts(241,14): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/services/app.user.service.ts(241,51): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/services/app.user.service.ts(242,14): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.
src/app/services/app.user.service.ts(242,58): error TS2339: Property 'dashboardSettings' does not exist on type 'UserSettingsInterface'.`

**Comment by NordicFlyer** [comment]
Compiles with NPM though with the aforementioned workaround.
[Terminal Saved Output 07022019.pdf](https://github.com/jimmykane/quantified-self/files/3350734/Terminal.Saved.Output.07022019.pdf)

**Comment by NordicFlyer** [comment]
@jimmykane I would like to use yarn in a straightforward yarn install/yarn run situation that is repeatable with each new master update.. Do you have any insight as to why there so many build errors via yarn?

**Comment by jimmykane** [comment]
The issue here looks like the yarn lock file brings back a wrong QSLib version. 
That is also why npm works. You can delete that file and should work (the yarn.lock) 

I am not sure why this quirkness. 

I ll double test today to close once and for all this issue

**Comment by NordicFlyer** [comment]
Yes indeed! That works. Thanks for the assistance.
